function init(self)
	msg.post(".", "acquire_input_focus")

end

function final(self)
	-- Return input focus when the object is deleted
	msg.post(".", "release_input_focus")
end

function on_input(self, action_id, action)
	
	if action_id == hash("esc") then
		if action.pressed then
			sound.play("/SoundManeger#menuInput")
			msg.post("@system:", "exit", { code = 0, resources = nil })
			
		end
	end
	
end